[supervisord]
nodaemon=true
logfile=/dev/null

[program:qdrant]
command=docker run --rm --name qdrant-server -p 6333:6333 -v /app/data/qdrant:/qdrant/storage qdrant/qdrant:latest
autostart=true
autorestart=true
startretries=5
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:llm]
command=python serve_llm.py
autostart=true
autorestart=true
startretries=5
startsecs=180
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=999

[program:app]
command=python app.py
autostart=true
autorestart=true
startretries=5
startsecs=210
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=999
